(ace-select-window)
(let* ((window (frame-selected-window))
       (windows '()))
  (push window windows)
  (dotimes (i 2)
    (setq window (split-window))
    (balance-windows (window-parent window))
    (push window windows))
  (window-make-atom (window-parent window)))

(balance-windows (window-atom-root (frame-selected-window)))
